### ISSUE TITLE
user

### ISSUE THREAD

**Issue by ghost** [quarkscript/linux-armv7-xe303c12-only#11]
How to Add Regular user to  (debian ) devuan lxqt ? and change the autologin to it ?

**Comment by quarkscript** [comment]
I guess same as for other linuxes:

`sudo useradd -m -g users -s /bin/bash user_name `
`sudo passwd user_name`

for 'nodm' the `/etc/nodm.conf` needs to be changed. Set the NODM_USER variable to the user who should log in automatically
