### ISSUE TITLE
Firewall 

### ISSUE THREAD

**Issue by ghost** [quarkscript/linux-armv7-xe303c12-only#2]
How easy to use firewall in this Arch bulid?
New kernel configuration http://www.linuxfromscratch.org/blfs/view/svn/postlfs/iptables.html dosent work for `iptables` and `nftables` after compiling and installing "linux pakage".
- `nftables` FAILURE:
my `systemctl status nftables` - https://pastebin.com/raw/QAt7Py1r
my `journalctl -xe` - https://pastebin.com/raw/MubQH2iy
- `nftables` Main Page - https://wiki.nftables.org/wiki-nftables/index.php/Main_Page#Introduction

Can't load `.rules` even width new kernel, the same output by every usable `iptabes` command
`iptables v1.8.6 (legacy): can't initialize iptables table filter: Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.`
`iptables-restore < /etc/iptables/empty.rules`
`iptables- F` - the same output

my `lsmod` - https://pastebin.com/raw/iGnXLnuS
my `ls /bin | grep table` - https://pastebin.com/raw/gaPd9vXD

**Comment by LokiInside** [comment]
> `iptables-restore < /etc/iptables/empty.rules`

**Comment by LokiInside** [comment]
`[xe@lightsys ~]$ ls /bin | grep table
arptables-nft
arptables-nft-restore
arptables-nft-save
ebtables-nft
ebtables-nft-restore
ebtables-nft-save
ip6tables
ip6tables-apply
ip6tables-legacy
ip6tables-legacy-restore
ip6tables-legacy-save
ip6tables-nft
ip6tables-nft-restore
ip6tables-nft-save
ip6tables-restore
ip6tables-restore-translate
ip6tables-save
ip6tables-translate
iptables
iptables-apply
iptables-legacy
iptables-legacy-restore
iptables-legacy-save
iptables-nft
iptables-nft-restore
iptables-nft-save
iptables-restore
iptables-restore-translate
iptables-save
iptables-translate
iptables-xml
portablectl
psfaddtable
psfgettable
psfstriptable
psfxtable
xtables-legacy-multi
xtables-monitor
xtables-nft-multi
[xe@lightsys ~]$`

**Comment by quarkscript** [comment]
iptables should work now. I have recompiled the kernel with almost all netfilter modules included. https://github.com/quarkscript/linux-armv7-xe303c12-only/releases/tag/5.9.12-2-archlinuxarm%2Fvoid-linux

**Comment by ghost** [comment]
> iptables should work now. I have recompiled the kernel with almost all netfilter modules included. https://github.com/quarkscript/linux-armv7-xe303c12-only/releases/tag/5.9.12-2-archlinuxarm%2Fvoid-linux

Can you share the config file, From compiling ?
Ufw/iptables works.
Or explain with modules you activated?

**Comment by quarkscript** [comment]
config is here https://github.com/quarkscript/linux-armv7-xe303c12-only/blob/master/archlinuxarm/linux_xe303c12/config

You can see the difference in history 
![Screenshot](https://user-images.githubusercontent.com/34370583/104626696-19047780-568e-11eb-8d29-ed10c633f8f8.png)

https://github.com/quarkscript/linux-armv7-xe303c12-only/commit/3ccbea28d5ed8609d4b47c97140e87af13467323#diff-8c27ef3ae831a80d28e24d3cd16c60f11fc5dda19d7e2e4d2f1f60adccb17e8f
