### ISSUE TITLE
xorg-server "libgl" // "works installed xterm" can be deleted 

### ISSUE THREAD

**Issue by ghost** [quarkscript/linux-armv7-xe303c12-only#3]
While tray to install minimal installation of xorg-server for openbox i get errors for every lbibgl. While other trays after installing whole gnome, it was working everything, my target is minimal openbox/wayland.
Seems problem with devfreq gpu.

[log xorg](https://pastebin.com/raw/1Cwa7vJm)

![20210108_221929.jpg](https://user-images.githubusercontent.com/75278757/104067038-b715bf00-5202-11eb-8e80-8d6e7d239937.jpg)
![20210108_222259.jpg](https://user-images.githubusercontent.com/75278757/104067071-c5fc7180-5202-11eb-9ac5-32996560f289.jpg)

**Comment by quarkscript** [comment]
Sorry for long reaction.

It looks like `xf86-video-armsoc-git` (archlinuxarm repo) was not installed. For minimal installation with X it required too.

If I not mistaken, wayland require drivers with 3D hardware acceleration, that is not available. linux-peach (chrome os) kernel from archlinuxarm repo could use hw 3d but I am not sure of compatibility with wayland. For use linux-peach, the root partition of the bootable system must be reformatted (from btrfs) to ext4. Disk partiton instruction from [archlinux|ARM](https://archlinuxarm.org/platforms/armv7/samsung/samsung-chromebook#installation) is valid for my recovery image too, you may simply recreate disk image with any size or any contents.

In my case `libglvnd` was installed. `Lxqt` with `openbox` slows down when mоving windows, with `xfwm4` as window manager `lxqt` run smoother.
