### ISSUE TITLE
Migration Internal to USB / arch

### ISSUE THREAD

**Issue by ghost** [quarkscript/linux-armv7-xe303c12-only#4]
Width the new kernel 5.10.3-3
After full migration of system to usb (3.0) but plugged in (2.0) external usb stick can't boot agin. So far I remember width some older kernels it was able to migrate everywhere where you wonted and it was working. This kernel width virtio drivers plase upload it I can't extract it width last kernel, if you have it already. 

This usb 3.0 for boot still impossible?
Thanks for possibility to install linux on this device, so farr i wonder how stable it is bulided from you.

**Comment by quarkscript** [comment]
This is a "BIOS" limitation of not using the usb3 port for booting. There shouldn't be any difference between usb3 stick and usb2 stick when connected to usb2 port.

What are the symptoms when it won't boot?
Does it make a double beep and return to the start screen? Or does it turn into a black screen? Or it writes some information like "... panic ... can't find root ..." ?

I haven't made any changes to the previous [recovery image](https://drive.google.com/file/d/17X-DlPpTQlipDR5Z5uZ29qQr8UXBKZED/view?usp=sharing), so it should be able to boot anyway. If this is not the case, you may have disabled external media booting, for example by disconnecting the battery or by disabling developer mode. If so, then you need to enable developer mode and enable USB booting from Chrome OS. 

Virtio driver needed when you want to run system from virtual machine like qemu (for example from regular PC).
To download kernel you may run from shell something like:
`wget https://github.com/quarkscript/linux-armv7-xe303c12-only/releases/download/5.10.3-xe303c12/linux-xe303c12-5.10.3-3-armv7h.pkg.tar.xz`
to extract
`tar -xf linux-xe303c12-5.10.3-3-armv7h.pkg.tar.xz` 
The kernel image required to run from qemu will be `boot/zImage` . Drivers will be `usr/lib/modules` . Flash image - `boot/vmlinux.kpart`

For example you want to install kernel to old recovery image from regular PC with linux (let's assume that you have already downloaded and unpacked the 5.10.3 kernel)

download with browser `https://drive.google.com/file/d/17X-DlPpTQlipDR5Z5uZ29qQr8UXBKZED/view?usp=sharing`

`tar -xf armv7hf.tar.zst `
`fdisk armv7hf.img `
press `p`
press `q`
you will see: 
```
Device       Start     End Sectors  Size Type
armv7hf.img1  8192   40959   32768   16M ChromeOS kernel
armv7hf.img2 40960 3854302 3813343  1.8G ChromeOS root fs
```
`mkdir test`
`sudo mount -o,offset=$((40960*512)) armv7hf.img test`
`cd test`
now you may download kernel image
`sudo wget https://github.com/quarkscript/linux-armv7-xe303c12-only/releases/download/5.10.3-xe303c12/linux-xe303c12-5.10.3-3-armv7h.pkg.tar.xz`
or
`sudo wget https://github.com/quarkscript/linux-armv7-xe303c12-only/releases/download/5.9.16/linux-xe303c12-5.9.16-1-armv7h.pkg.tar.xz
tar -xf linux-xe303c12-5.9.16-1-armv7h.pkg.tar.xz`
or 
`sudo wget https://github.com/quarkscript/linux-armv7-xe303c12-only/releases/download/5.9.12-2-archlinuxarm%2Fvoid-linux/linux-xe303c12-5.9.12-2-armv7h.pkg.tar.xz`

`cd ../`
`sudo umount test`
now you can run qemu
`qemu-system-arm -machine virt -m 1024 -kernel boot/zImage -append "root=/dev/vda2" -serial stdio -drive if=none,file=armv7hf.img,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 `
user `root`
password `root`
```
[root@lightsys ~]# ls /
bin   etc   linux-xe303c12-5.9.12-2-armv7h.pkg.tar.xz  proc  sbin  tmp
boot  home  mnt                                        root  srv   usr
dev   lib   opt                                        run   sys   var
[root@lightsys ~]# pacman -U /linux-xe303c12-5.9.12-2-armv7h.pkg.tar.xz
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) linux-xe303c12-5.9.12-2

Total Installed Size:  64.27 MiB
Net Upgrade Size:       3.04 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) upgrading linux-xe303c12                     [######################] 100%

Chrome OS kernel partition did not detected.
You must reflash kernel manually.
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Updating module dependencies...
(3/3) Updating linux-xe303c12 module dependencies...

[root@lightsys ~]# blkid 
/dev/vda2: LABEL="Root" UUID="77fe42a9-924b-472f-94ca-3e26ab7987ca" UUID_SUB="54dc2f44-8c7d-45ec-8fc5-4e7d086ca6cc" BLOCK_SIZE="4096" TYPE="btrfs" PARTLABEL="Root" PARTUUID="c4bcda61-d9c5-1847-9e4a-46bcaf41e281"
/dev/vda1: PARTLABEL="Kernel" PARTUUID="200076f3-0e02-024a-9475-45d228e7146a"
[root@lightsys ~]# dd if=/boot/vmlinux.kpart of=/dev/vda1
13136+0 records in
13136+0 records out
6725632 bytes (6.7 MB, 6.4 MiB) copied, 3.38266 s, 2.0 MB/s
[root@lightsys ~]# poweroff

```
Now you have disk image with another kernel installed

Or without qemu you may simply extract kernel with tar command, copy `usr/lib/modules` to "flash stick root partition/usr/lib/modules" and flash image like `sudo dd if=boot/vmlinux.kpart of="first partition of flash stick"`

**Comment by ghost** [comment]
.
In past I was find whole Google thing about uboot for xe303c12 with customs, I have dream about usb booting 3.0.

I give a reply now I'm testing.
😘

**Comment by quarkscript** [comment]
https://archlinuxarm.org/forum/viewtopic.php?t=11812
but with my kernel /dev/spidev* is not available, driver may be required

https://archlinuxarm.org/forum/viewtopic.php?f=27&t=4016&p=30291&hilit=boot+mode+configuration+resistors+Chromebook#p30291

**Comment by ghost** [comment]
My dear thanks for every advice.
It works btrfs volume is recognized. (USB 126 GB) keep going it's great device 👍
USB 3.0 I do next it's great device to do perfection os on it because arm become more and more nice training I mean 😉.
Maybe timeout monitoring, time shuld be changed sometimes by update normal packages I get timeout messeges.


Some link to this website [Google arm chromebook](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/samsung-arm-chromebook)
