### ISSUE TITLE
BlackArch

### ISSUE THREAD

**Issue by ghost** [quarkscript/linux-armv7-xe303c12-only#5]
[blackarcharm](https://blackarch.org/downloads.html#install-repo)

While tray to install it from repo i can't get it to work its a issuse from distro or from repo ?
Seems like pacman not accept gpg. Uncomment of mirrors not help any advice ?

**Comment by quarkscript** [comment]
Black Arch dropped support for the armv7h architecture 2 years ago (or so). 
You may try to build the required pkg from their github repo like:
```
git clone https://github.com/BlackArch/blackarch.git

# add armv7h architecture to all PKGBUILDs
for i in $(find -depth -name PKGBUILD | sed 's/\.\///g'); do  sed -i "s/arch=('x86_64'/arch=('x86_64' 'armv7h'/g" $i ; done

cd blackarch/packages/
ls | less # press 'q' to exit from less
cd to 'needed package'

# build
makepkg

# install
sudo pacman -U 'builded package'
```
In case required package exist in [AUR](https://aur.archlinux.org) you may try to build it (and dependencies) with [sfslib](https://github.com/quarkscript/Simple_func_scripts) like `./sfslib armget 'pkgname'`

**Comment by ghost** [comment]
compilled blackman and installed then i was run installer of tools
#non armv7h are just ignorred while compiling and installing width blackman
# Download, compile and install all BlackArch tools

$ sudo blackman -l
$ sudo blackman -g blackarch-wireless

(Many Packages are not supported)

This will be work width Menus to clear it up.

![20210208_192212.jpg](https://user-images.githubusercontent.com/75278757/107264251-0c7ffe80-6a43-11eb-86cc-e5635a52a29f.jpg)

**Comment by quarkscript** [comment]
It's good. At least some tools are available. 

If you are interested in a pentest from this device, you may be interested in another distribution. Kali still provides an x86 (32-bit) version, so it's likely that kali armv7hf (also a 32-bit version) might contain more tools out of the box.
I have updated the build script for the Kali image, but need some time to test it. https://github.com/quarkscript/xe303c12_play_linux
