### ISSUE TITLE
Void (Linux)

### ISSUE THREAD

**Issue by ghost** [quarkscript/linux-armv7-xe303c12-only#6]
What a tarball is used on xe303c12 of void linux from arm section ?
In xbps pakage in aur are missing metadata and can't be installed. Meanwhile i test kali.

**vmlinux.kpart** from last compiled kernel **linux_xe303c12-5.10.13_1.armv7l.xbps** on **/dev/mmcblk1p1** with dd
**void-armv7l-ROOTFS-20191109.tar.xz** extracted with **tar -xvf** on mounted (ext4) **/dev/mmcblk1p2** 
and i can't boot, get black screen (no beep signal)

**Comment by quarkscript** [comment]
Probably it boot, but no video driver. Try to extract usr/lib/modules/* from **linux_xe303c12-5.10.13_1.armv7l.xbps** and copy  to the 'root partition'/usr/lib/modules/

**Comment by ghost** [comment]
worked after update repositories and tray to install mc/nano some **library.so.6** error any advice after reboot machine just is turning off and is needed new tarball 
Error while updating xbps
![20210212_130217.jpg](https://user-images.githubusercontent.com/75278757/107765888-e607df00-6d32-11eb-8deb-c781082518f0.jpg)

**Comment by quarkscript** [comment]
Try this one https://alpha.de.repo.voidlinux.org/live/20201224/void-armv7l-ROOTFS-20201224.tar.xz

https://docs.voidlinux.org/installation/guides/chroot.html#install-base-system-rootfs-method-only

**Comment by ghost** [comment]
Great it's working 🙂.
