### ISSUE TITLE
2.7 Exabyte

### ISSUE THREAD

**Issue by ghost** [quarkscript/linux-armv7-xe303c12-only#7]
Install sosumi replace common and find the code 
https://files.fm/u/82zpbg9yc
https://uptobox.com/f9ugkg0vim8e
common2_7_EB_common_snap_sosumi_digital_god_and_jan_sloot_script_as_dvd_drive.tar.gz

**Comment by quarkscript** [comment]
I think it will not run on xe303c12-chromebook (2 Gb of ram and 32 bit  cpu)
This software uses qemu to run the system and requires 10Gb of ram and 64 bit cpu.
